### PR TITLE
V0.10.2

### PR DESCRIPTION
**Pull request by MattTriano**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [N/A] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MattTriano** [comment]
@pmlandwehr  I see you have some recent activity on GitHub, so hopefully this reaches you. 

Could you take a look at this and merge it in if it looks ok? I'd love to help out maintaining conda-forge packages, so if there are any issues with my update, I'd greatly appreciate any advice (I started reading through conda-forge and conda-build docs specifically out of a desire to update the conda-forge version of this package).

Thanks!

**Comment by MattTriano** [comment]
@conda-forge-admin, please add user @MattTriano

**Comment by MattTriano** [comment]
@ocefpaf Could you review this MR (or even better the MR I submitted for v0.12.5; I'm only summoning you via this one as it shows more history)? Thanks so much for the work you do for conda-forge.

**Comment by ocefpaf** [comment]
Thanks for helping out with this package! It was kind of abandoned.

**Pull request merged**
